# Generated by Django 4.1 on 2023-07-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("App_CS", "0004_imagen_id_imagen_show_id_alter_imagen_rodeo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagen",
            name="id",
        ),
        migrations.RemoveField(
            model_name="imagen_show",
            name="id",
        ),
        migrations.AlterField(
            model_name="imagen",
            name="rodeo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="App_CS.rodeo",
            ),
        ),
        migrations.AlterField(
            model_name="imagen_show",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="App_CS.show",
            ),
        ),
    ]
