# Generated by Django 4.1 on 2023-07-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("App_CS", "0005_remove_imagen_id_remove_imagen_show_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagen",
            name="rodeo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="App_CS.rodeo",
            ),
        ),
        migrations.AlterField(
            model_name="imagen_show",
            name="show",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="App_CS.show",
            ),
        ),
    ]
